# In your home directory make directory docker_volume 
# This compose is build and tested on MAC. Other OS might require some tweaks
# This is experimental development stack with no any security practice in place
version: "3.7"
services:
  influxdb_dev:
    image: influxdb:latest
    container_name: influxdb-dev-local
    restart: always
#    network_mode: "bridge"
    networks:
      - dev_net
    env_file:
      - ./influxdb/influxdb.env
    ports:
      - 8086:8086
    volumes:
      - ${HOME}/docker_volumes/influxdb-dev-local-volume:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana_dev:
    image: grafana/grafana:latest
    container_name: grafana-dev-local
    restart: always
#    network_mode: "bridge"
    networks:
      - dev_net
    ports:
      - "3000:3000"
    env_file:
      - './grafana/grafana.env'
    volumes:
      - ${HOME}/docker_volumes/grafana-dev-local-volume:/var/lib/grafana

  portainer_dev:
    image: portainer/portainer
    container_name: portainer-dev-local
    restart: always
#   network_mode: "bridge"
    networks:
      - dev_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/docker_volumes/portainer-dev-local-volume:/data
#    command: --admin-password='Password1'
    ports:
      - "9000:9000"
      - "8000:8000"

# Quick test from CLI to validate that you can see in DB all Docker engine matric
# curl -i -G 'http://localhost:8086/query?db=MetricStore' -u admin:Password1 --data-urlencode 'q=SELECT * FROM "MetricStore"'
# curl -i -G 'http://localhost:8086/query?db=MetricStore' --data-urlencode 'q=SELECT * FROM "MetricStore"'

  telegraf_dev:
    image: telegraf:alpine
    container_name: telegraf-dev-local
    env_file:
      - ./telegraf/telegraf.env
    depends_on:
      - "influxdb_dev"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    networks:
      - dev_net
    restart: always

  kapacitor_dev:
    image: kapacitor
    container_name: kapacitor-dev-local
    depends_on:
      - "influxdb_dev"
    env_file:
      - ./kapacitor/kapacitor.env
    volumes:
      - ${HOME}/docker_volumes/kapacitor-dev-local-volume:/var/lib/kapacitor
    networks:
      - dev_net
    ports:
      - "9092:9092"
    restart: always

  chronograf_dev:
    image: chronograf
    container_name: cronograf-dev-local
    depends_on:
      - "influxdb_dev"
    volumes:
      - ${HOME}/docker_volumes/chronograf-dev-local-volume:/var/lib/chronograf
    networks:
      - dev_net
    ports:
      - "8888:8888"
    restart: always
    command: ["chronograf", "--influxdb-url=http://influxdb-dev-local:8086"]

# TEXT container with shell and you can install any tools needed to validate test network or others
# To test pings and bridge host networks and their links and dns intercept on mac or windows etc. 
# Run command to iupdate and install utils 
# -->> apt update && apt upgrade && apt install iputils-ping

#  ubuntu_tester:
#    image: ubuntu:latest
#    container_name: ubuntu_tester_1
#    command: "sleep infinity"
#    networks:
#      - dev_net

# Creating new bridge network as default bridge don support links and its not recommended to use it
networks:
  dev_net:
    name: dev_net
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.16.0/24
# Set subnet as random subnets can overlay with your own I know what a chance ? it did happen so I had to set it