# In your home directory make directory docker_volume 
# This compose is build and tested on MAC. Other OS might require some tweaks
# This is experimental development stack with no any security practice in place
version: "3.7"
services:
  influxdb_dev:
    image: influxdb:latest
    container_name: influxdb-dev-local
    restart: on-failure
#    network_mode: "bridge"
    networks:
      - dev_net
    env_file:
      - ./influxdb/influxdb.env
    ports:
      - 8086:8086
    volumes:
      - ${HOME}/docker_volumes/influxdb-dev-local-volume:/var/lib/influxdb

  grafana_dev:
    image: grafana/grafana:latest
    container_name: grafana-dev-local
    restart: on-failure
#    network_mode: "bridge"
    networks:
      - dev_net
    ports:
      - "3000:3000"
    env_file:
      - './grafana/grafana.env'
    volumes:
      - ${HOME}/docker_volumes/grafana-dev-local-volume:/var/lib/grafana

#
  portainer_dev:
    image: portainer/portainer
    container_name: portainer-dev-local
    restart: on-failure
#   network_mode: "bridge"
    networks:
      - dev_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/docker_volumes/portainer-dev-local-volume:/data
    command: --admin-password='Password1'
    ports:
      - "9000:9000"

# TEXT container with shell and you can install any tools needed to validate test network or others
# To test pings and bridge host networks and their links and dns intercept on mac or windows etc. 
# Run command to iupdate and install utils 
# -->> apt update && apt upgrade && apt install iputils-ping

  ubuntu_tester:
    image: ubuntu:latest
    container_name: ubuntu_tester_1
    command: "sleep infinity"
    networks:
      - dev_net

networks:
  dev_net:
    name: dev_net

  