version: "3.7"
services:
  influxdb_dev:
    image: influxdb:latest
    container_name: influxdb-dev-local
    restart: on-failure
    network_mode: "bridge"
    env_file:
      - ./influxdb/influxdb.env
    ports:
      - 8086:8086
    volumes:
      - ${HOME}/docker_volumes/influxdb-dev-local-volume:/var/lib/influxdb

  grafana_dev:
    image: grafana/grafana:latest
    container_name: grafana-dev-local
    restart: on-failure
    network_mode: "bridge"
    ports:
      - "3000:3000"
    env_file:
      - './grafana/grafana.env'
    volumes:
      - ${HOME}/docker_volumes/grafana-dev-local-volume:/var/lib/grafana

  portainer_dev:
   image: portainer/portainer
   container_name: portainer-dev-local
   restart: on-failure
   network_mode: "bridge"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${HOME}/docker_volumes/portainer-dev-local-volume:/data
#   command: --admin-password-file ./portainer/portainer_password
   ports:
     - "9000:9000"