version: "3.7"
services:
  influxdb-dev:
    image: influxdb:1.7.7
    container_name: influxdb-dev-local
    env_file:
      - ./influxdb/influxdb.env
    ports:
      - 8086:8086
    volumes:
      - "influxdb-dev-local-volume:/var/lib/influxdb"

volumes:
  influxdb-dev-local-volume:


