version: "3.7"
services:
  telegraf_dev:
    image: telegraf:alpine
    container_name: telegraf-agent-dev
    env_file:
      - ./telegraf/telegraf.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    networks:
      - dev_net
    restart: always

networks:
  dev_net:
    name: dev_net